spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital?useUnicode=true&charset=utf8mb4&useSSL=false&serverTimezone=GMT%2B8&amp
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
  port: 8080

swagger:
  base-package: net.vivipara
  base-path: /**

upload-server:
  qi-niu:
    access: oTlxfX9M3DFnfbPUPyubhBCHvYvtNLwEETfJkfSS
    secret: jPVSgKbNGYbh6IwM5fb0D9iljpsTwSgNjM2DxwiO
    bucket: myblog